name: Niall McCormack
favicon: null
layout_spectrum: 0.06808688025921583
typography_spectrum: 0.15962033835239708
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.516481542494148
  lightness: 0.6742703139316291
  saturation: 0.812402178067714
  rhythmicContrast: 0.048729512142017484
purpose: []
